# Generated by Django 5.0.6 on 2024-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_technician',
            new_name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='poste',
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_employer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_commerciaux',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_ops',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
