# Generated by Django 5.0.6 on 2024-07-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_is_commerciaux_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debit',
        ),
    ]
